apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service-canary
spec:
  type: LoadBalancer  # Specifies the type of service
  selector:
    app: train-schedule
    track: canary       # Selects pods with labels app=train-schedule and track=canary
  ports:
  - protocol: TCP
    port: 8080          # Port exposed by the service within the cluster
    targetPort: 8080    # Port on the pods to which the traffic will be forwarded



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment-canary
  labels:
    app: train-schedule
spec:
  replicas: 3  # Replace with your desired number of replicas
  selector:
    matchLabels:
      app: train-schedule
      track: canary
  template:
    metadata:
      labels:
        app: train-schedule
        track: canary
    spec:
      containers:
      - name: train-schedule
        image: awab82002/train:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
